name: wya-scheme

dependencies:
  - base
  - parsec
  - pretty-simple
  - text
  - array
  - HUnit
  - raw-strings-qq
  - mtl

executables:
  wya-scheme-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -Wno-unused-do-bind

tests:
  hunit:
    main: Tests.hs
    source-dirs:
      - app
      - test
