name: wya-scheme

dependencies:
  - base
  - parsec
  - text
  - array
  - mtl
  - containers


executables:
  wya-scheme-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -Wno-unused-do-bind
