name: wya-scheme

dependencies:
  - base
  - parsec
  - pretty-simple
  - text
  - array
  - HUnit
  - raw-strings-qq
  - mtl

executables:
  wya-scheme-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wno-unused-do-bind

tests:
  parser-tests:
    main: Tests.hs
    source-dirs:
      - app
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
