name: wya-scheme

dependencies:
  - base >= 4.7 && < 5
  - parsec
  - pretty-simple
  - text
  - array
  - HUnit
  - raw-strings-qq

executables:
  wya-scheme-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wno-unused-do-bind

tests:
  hunit:
    main: Tests.hs
    source-dirs:
      - app
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
