`(,(+ 1.2 4/5 5)
  ,(* 2 3+1.5i)
  ,(symbol? 'foo)
  `(1 ,"foo" ,(2 ,(/ 1.0 5)))
  ,(string=? "foo" "bar")
  ,(string=? "foo" "foo")
  ,(= 1 1)
  ,(= 1 1.0)
  (expect "1"     : ,(car '(1 2)))
  (expect "1"     : ,(car '(1 . 2)))
  (expect "[2]"   : ,(cdr '(1 2)))
  (expect "2"     : ,(cdr '(1 . 2)))
  (expect "[1,2]" : ,(cons 1 '(2)))
  (expect true    : ,(eqv? 1 1))
  (expect false   : ,(eqv? 1 2))
  (expect true    : ,(equal? '(1 2 3) '(1 2 3)))
  (expect false   : ,(equal? '(1 2 3) '(2 2 3)))
  )

(define foo 1)

`(expect 2: ,(+ 1 foo))

(set! foo 2)

`(expect 3: ,(+ 1 foo))
